# Generated by Django 3.0.2 on 2020-01-12 13:11

from django.db import migrations

bootstrap_version = "4.4.1"
jquery_version = "3.3.1"
popover_version = "1.14.3"
urls_settings = {
    "css_url": {
        "library": 1,
        "href": f"https://stackpath.bootstrapcdn.com/bootstrap/{bootstrap_version}/css/bootstrap.min.css",
        "integrity": "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh",
        "crossorigin": "anonymous",
    },
    "javascript_url": {
        "url": f"https://stackpath.bootstrapcdn.com/bootstrap/{bootstrap_version}/js/bootstrap.min.js",
        "integrity": "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6",
        "crossorigin": "anonymous",
    },
    "javascript_bundle_url": {
        "url": f"https://stackpath.bootstrapcdn.com/bootstrap/{bootstrap_version}/js/bootstrap.bundle.min.js",
        "integrity": "sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm",
        "crossorigin": "anonymous",
    },
    "jquery_url": {
        "url": f"https://code.jquery.com/jquery-{jquery_version}.min.js",
        "integrity": "sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT",
        "crossorigin": "anonymous",
    },
    "jquery_slim_url": {
        "url": f"https://code.jquery.com//jquery-{jquery_version}.slim.min.js",
        "integrity": "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo",
        "crossorigin": "anonymous",
    },
    "popper_url": {
        "url": f"https://cdnjs.cloudflare.com/ajax/libs/popper.js/{popover_version}/umd/popper.min.js",
        "integrity": "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49",
        "crossorigin": "anonymous",
    }
}


def forwards(apps, schema_editor):
    IncludeBootstrap = apps.get_model('django_include_bootstrap', 'IncludeBootstrap')


def backwards(apps, schema_editor):
    IncludeBootstrap = apps.get_model('django_include_bootstrap', 'IncludeBootstrap')


class Migration(migrations.Migration):
    dependencies = [
        ('django_include_bootstrap', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
